Adding push/pull for notes for git repo

diff --git a/zsh/functions/notes b/zsh/functions/notes
--- a/zsh/functions/notes
+++ b/zsh/functions/notes
@@ -22,15 +22,25 @@ notes () {
 
   cmd=nvim
 
+  _notes_error() {
+    echo "${RED}$1${NC}"
+    if [ $# -eq 1 ]; then
+      _notes_help
+    fi
+    return 0
+  }
+
   _notes_help() {
     echo "\nNotes - Opens notes in the configured notes directory\n"
     echo "Commands:\n"
     echo "notes cd - Change to the notes directory"
     echo "notes ls [search] - List all notes in the notes directory. Add an optional search pattern."
+    echo "notes push <message> - Commits and pushes any changes to the git repo. Message is required for the commit."
+    echo "notes pull - Pulls any upstream changes into the local repo."
+    echo "notes sync <message> - Commit, push, and pull all changes."
     echo "notes <filename>[.md] - Open the file for editing. If no extension is on the filename, .md is appended to the file name.\n"
     echo "Use tab-completion for files"
   }
-
 
   # Look for an overriden env var
   [ -z "$NOTES_DIR" ] && $NOTES_DIR="$HOME/notes"
@@ -53,13 +63,34 @@ notes () {
         ls -l -1 "$NOTES_DIR"
       fi
       ;;
+    push)
+      if [ ! $# -eq 2 ]; then
+        _notes_error "Please add a commit message."
+      else
+        cd "$NOTES_DIR"
+        git add -A
+        git commit -m "$1"
+        git push
+        cd -
+      fi
+      ;;
+    pull)
+      cd "$NOTES_DIR"
+      # If there are uncommitted changes, stop and let me know
+      if ! git diff-index --quiet HEAD --; then
+        _notes_error "There are uncommited changes you should review before pulling." 0
+        git status
+      else
+        git pull
+        cd -
+      fi
+      ;;
     help|-h|--help)
       _notes_help
       ;;
     *)
       if [ $# -eq 0 ]; then
-        echo "${RED}Please enter a file to open.${NC}"
-        _notes_help
+        _notes_error "Please enter a file to open."
       else
         pushd "$NOTES_DIR"
         case "$1" in
